In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Fish.csv")

In [3]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
df.describe()

Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [6]:
df.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [7]:
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns.tolist()

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

In [25]:
df.tail()

Species    Weight   Length1   Length2   Length3    Height     Width
154   Smelt -1.082039 -1.479903 -1.517960 -1.540309 -1.610359 -1.799403
155   Smelt -1.078676 -1.459833 -1.499238 -1.531669 -1.530878 -1.873547
156   Smelt -1.082039 -1.419692 -1.443072 -1.505748 -1.566687 -1.881402
157   Smelt -1.061022 -1.309305 -1.321378 -1.384784 -1.427243 -1.398568
158   Smelt -1.060461 -1.249094 -1.255851 -1.298381 -1.413341 -1.510440

In [10]:
print(df.columns)

Index(['Species', 'Weight', 'Length1', 'Length2', 'Length3', 'Height',
       'Width'],
      dtype='object')


In [23]:
df['Species'].value_counts()

Species
Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: count, dtype: int64

In [11]:
x=df.drop('Species',axis=1)
y=df['Species']

In [12]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Encode the target variable (y)
y_encoded = label_encoder.fit_transform(y)

# Now y_encoded contains integer labels corresponding to the unique classes in y
print(y_encoded)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 6 6 6 6 6 1 1 1 1 1 1 1 1 1 1 1 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5
 5 5 5 5 5 5 5 5 5 5 5]


In [24]:
joblib.dump(label_encoder, 'label_encoder.pkl')

['label_encoder.pkl']

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y_encoded,test_size=0.2)

In [14]:
import xgboost as xgb
xgb_clf = xgb.XGBClassifier(objective='multi:softmax', num_class=len(set(y_train)),seed=42)
xgb_clf.fit(x_train,y_train,early_stopping_rounds=10,eval_metric='mlogloss', eval_set=[(x_test, y_test)])

[0]	validation_0-mlogloss:1.59591
[1]	validation_0-mlogloss:1.38332
[2]	validation_0-mlogloss:1.22398
[3]	validation_0-mlogloss:1.11461
[4]	validation_0-mlogloss:1.03266
[5]	validation_0-mlogloss:0.97849
[6]	validation_0-mlogloss:0.92481
[7]	validation_0-mlogloss:0.90701
[8]	validation_0-mlogloss:0.87644
[9]	validation_0-mlogloss:0.85276
[10]	validation_0-mlogloss:0.84845
[11]	validation_0-mlogloss:0.84119
[12]	validation_0-mlogloss:0.84402
[13]	validation_0-mlogloss:0.84401
[14]	validation_0-mlogloss:0.83911
[15]	validation_0-mlogloss:0.83288
[16]	validation_0-mlogloss:0.82868


C:\Users\arunk\AppData\Roaming\Python\Python311\site-packages\xgboost\sklearn.py:889: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\arunk\AppData\Roaming\Python\Python311\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


[17]	validation_0-mlogloss:0.82039
[18]	validation_0-mlogloss:0.82236
[19]	validation_0-mlogloss:0.81438
[20]	validation_0-mlogloss:0.81544
[21]	validation_0-mlogloss:0.81587
[22]	validation_0-mlogloss:0.81698
[23]	validation_0-mlogloss:0.81174
[24]	validation_0-mlogloss:0.80597
[25]	validation_0-mlogloss:0.80977
[26]	validation_0-mlogloss:0.80633
[27]	validation_0-mlogloss:0.80579
[28]	validation_0-mlogloss:0.80318
[29]	validation_0-mlogloss:0.80139
[30]	validation_0-mlogloss:0.79891
[31]	validation_0-mlogloss:0.79666
[32]	validation_0-mlogloss:0.79703
[33]	validation_0-mlogloss:0.79598
[34]	validation_0-mlogloss:0.79693
[35]	validation_0-mlogloss:0.79765
[36]	validation_0-mlogloss:0.80537
[37]	validation_0-mlogloss:0.80449
[38]	validation_0-mlogloss:0.80600
[39]	validation_0-mlogloss:0.80968
[40]	validation_0-mlogloss:0.80481
[41]	validation_0-mlogloss:0.80810
[42]	validation_0-mlogloss:0.81440
[43]	validation_0-mlogloss:0.81300


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=7,
              num_parallel_tree=None, ...)

In [16]:
y_pred=xgb_clf.predict(x_test)
y_pred

array([2, 0, 2, 4, 2, 0, 0, 0, 0, 0, 2, 4, 0, 2, 4, 6, 3, 5, 2, 3, 2, 2,
       1, 2, 3, 2, 1, 2, 1, 6, 1, 2])

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(classification_report(y_test,y_pred))

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      0.80      0.89         5
           2       0.67      0.89      0.76         9
           3       1.00      1.00      1.00         3
           4       0.67      0.33      0.44         6
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.78        32
   macro avg       0.76      0.72      0.73        32
weighted avg       0.81      0.78      0.78        32

Accuracy: 0.78125
Confusion Matrix:
[[7 0 0 0 0 0 0]
 [0 4 0 0 1 0 0]
 [0 0 8 0 0 0 1]
 [0 0 0 3 0 0 0]
 [0 0 3 0 2 0 1]
 [0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0]]


In [36]:
xgb_clf.save_model('Fish_Classification_Model.h5')

C:\Users\arunk\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:160: UserWarning: [22:09:25] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\c_api\c_api.cc:1240: Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.
  warnings.warn(smsg, UserWarning)


In [18]:
import joblib
joblib.dump(xgb_clf, "Fish_Classification_Model.pkl")

['Fish_Classification_Model.pkl']